# Generated by Django 3.0.7 on 2020-06-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Folder_id',
            field=models.CharField(max_length=100),
        ),
    ]
