# Generated by Django 3.0.7 on 2020-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_lib', '0003_updatelinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelinks',
            name='Folder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
