# Generated by Django 3.0.7 on 2020-06-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_lib', '0004_updatelinks_folder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatelinks',
            old_name='Folder_id',
            new_name='Main_folder_id',
        ),
    ]
