# Generated by Django 3.0.7 on 2020-06-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_lib', '0005_auto_20200630_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
