# Generated by Django 3.0.7 on 2020-07-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_lib', '0006_auto_20200630_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
