# Generated by Django 3.0.7 on 2020-07-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_lib', '0007_book_book_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
