# Generated by Django 3.0.7 on 2020-07-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_lib', '0008_delete_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Text', models.TextField()),
            ],
        ),
    ]
