# Generated by Django 3.0.7 on 2020-07-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_lib', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
